# Generated by Django 2.2.3 on 2019-07-11 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_see', models.CharField(max_length=100)),
                ('visit_purpose', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
                ('visit_code', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorDetailChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('field', models.CharField(max_length=100)),
                ('from_value', models.CharField(max_length=100)),
                ('to_value', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors_guestbook.VisitHistory')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors_guestbook.Visitor')),
            ],
        ),
        migrations.AddField(
            model_name='visithistory',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors_guestbook.Visitor'),
        ),
    ]
